### ISSUE TITLE
Getting a maximum file size with default settings.

### ISSUE THREAD

**Issue by sorenwacker** [np-8/dash-uploader#105]
I am trying to upload around 900 files a 15MB I get the following popup: 

Total file size too large (11547.9 Mb) ! Maximum total filesize is: 5120.0 Mb

Although, I did not set a  maximum file size in the plugin. 

        html.H3("Upload MS-files"),
        html.Div(
            du.Upload(
                id="ms-uploader",
                filetypes=["tar", "zip", "mzxml", "mzml", "mzXML", "mzML"],
                upload_id=uuid.uuid1(),
                max_files=10000,
                pause_button=True,
                cancel_button=True,
                text="Upload mzXML/mzML files.",
            ),
            style={
                "textAlign": "center",
                "width": "100%",
                "padding": "0px",
                "margin-bottom": "20px",
                "display": "inline-block",
            },
        ),

I thought without that setting the file size is unlimited?

**Comment by fohrloop** [comment]
Which version of dash-uploader are you using?

**Comment by Kevin-Krucki** [comment]
I am also getting this issue using the latest version 0.7.0a1. Is there a known fix for this issue or a field I can set to change it?

**Comment by fohrloop** [comment]
Hi,

You could try setting the `max_total_size` argument of the `Upload` component. From [dash_uploader/upload.py](https://github.com/np-8/dash-uploader/blob/dev/dash_uploader/upload.py#L95):

```python
def Upload(
    id="dash-uploader",
    text="Drag and Drop Here to upload!",
    text_completed="Uploaded: ",
    text_disabled="The uploader is disabled.",
    cancel_button=True,
    pause_button=False,
    disabled=False,
    filetypes=None,
    max_file_size=1024,
    max_total_size=5 * 1024,   # <--- this one
    chunk_size=1,
    default_style=None,
    upload_id=None,
    max_files=1,
):
"""
...
    max_total_size: numeric
        The maximum total size of files to be uploaded
        in Megabytes. Default: 5*1024 (5Gb)
...
"""
```

Seems that the [docs](https://github.com/np-8/dash-uploader/blob/dev/docs/dash-uploader.md#duupload) have not been updated for the most recent changes.

**Comment by CShaw-1** [comment]
I'm running into a similar issues uploading a file that's even 1,239kb. Getting the error: "Unexpected error while uploading FILENAME! Please reupload the file." Can't seem to find a fix anywhere.
