### ISSUE TITLE
[BUG] v0.2.2 pip install error

### ISSUE THREAD

**Issue by MM-Lehmann** [np-8/dash-uploader#2]
0.2.2 cannot be installed via pip:
```
ERROR: Command errored out with exit status 1:
     command: /home/user/PycharmProjects/columbus/venv3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ea6fq8dy/dash-uploader/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ea6fq8dy/dash-uploader/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ea6fq8dy/dash-uploader/pip-egg-info
         cwd: /tmp/pip-install-ea6fq8dy/dash-uploader/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ea6fq8dy/dash-uploader/setup.py", line 8, in <module>
        with open('docs/README-PyPi.md', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'docs/README-PyPi.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

it seems the README-PyPi.md is missing from the package

**Comment by thepycoder** [comment]
I have the same issue.
A workaround is cloning the repository and running `python setup.py install`

This same `setup.py` is the one that refers to the `'docs/README-PyPi.md'` which triggers the error.

**Comment by np-8** [comment]
Thanks for reporting! I will fix it when I get back on my computer. The 0.2.0 version is identical to 0.2 2. and should be working with pip. The only difference in 0.2.1  and 0.2.2. is that I included documentation for PyPi, and those needed version bumps (can not update readme on PyPi without changing the package version. How convenient..)

**Comment by np-8** [comment]
Fixed in **v. 0.2.3** (https://github.com/np-8/dash-uploader/commit/029aa557db2b068f2f545f3f7687144a944c12cb). The `docs/README-PyPi.md` was missing from the `MANIFEST.in`.
