### ISSUE TITLE
Some suggestion / feature request multi-file upload.

### ISSUE THREAD

**Issue by sorenwacker** [np-8/dash-uploader#20]
I like the tool a lot. It solves the problem of the progress bar. It would be nice to have multi-file upload enabled. Would it be possible to simply wrap the upload routine into a for loop and upload files one by one? With potentially a second progress bar that shows the overall progress.

**Comment by np-8** [comment]
Hi @soerendip, thank you! I think the multi-upload support is doable, but it has some challenges. You can read a [related thread here](https://github.com/np-8/dash-uploader/issues/5).

In short, it would require some changes to the React/JS side of dash-uploader (a bit more than adding a for-loop). There is also a [bug](https://github.com/23/resumable.js/issues/416) in the used resumable.js that causes only one folder to be uploaded on Chrome, even if multiple folders are selected. Therefore, it would still not be 100% perfect but surely could be better than the current solution.  

I could also consider migrating from resumable.js to for example [rc-upload](https://github.com/react-component/upload) which seems to support multifile uploads. I should do some JS package scouting and see what's available. Of course, selecting new JS package to do the job would need some testing, and robustness & package maturity is also important. If anyone has suggestions, please let me know!

Yeah in many cases showing the overall progress would make more sense. Maybe this should be configurable option (which progressbar to show).

I fully support the multi-file upload idea and wish that some day dash-uploader will have excellent multi-file support.

**Comment by fohrloop** [comment]
This is now fixed in the [`dev`](https://github.com/np-8/dash-uploader/tree/dev)  branch in 511557f587a02fbae6a0462e5074abd449c14bd0. The fix will be included in the dash-uploader 0.7.0 release.
