### ISSUE TITLE
How to install a development version? 

### ISSUE THREAD

**Issue by sorenwacker** [np-8/dash-uploader#48]
Hi, I tried cloning the repository and `pip install .` , but that resulted in 

>     error: package directory 'dash_uploader/_build' does not exist

I wonder what additional steps need to be done and I could not find instructions in the docs.

**Comment by sorenwacker** [comment]
Ok, I think I figured it out.

    npm install
    npm run build
    pip install -e .

**Comment by np-8** [comment]
Glad that you figured it out! There is also some additional info in the [CONTRIBUTING.md](https://github.com/np-8/dash-uploader/blob/dev/docs/CONTRIBUTING.md) if you are interested in contributing to the package :)

**Comment by sorenwacker** [comment]
Ok, I will read that.... after just making my first pull request...
