### ISSUE TITLE
du-uploader not compatible with Dash latest version 2.0.0

### ISSUE THREAD

**Issue by vishnuav08** [np-8/dash-uploader#51]
Hi,

I have installed the dash uploader recently and noticed that it's not compatible with dash 2.0.0. The HTML and DCC import has been changed in-dash 2.0.0 from 
import dash_html_components as html 
to 
from dash import html

Just wondering if there is any plan to release  du-uploader compatible with Dash 2.0.0

Thanks

**Comment by np-8** [comment]
Hi,

The `dash-uploader` is compatible with `dash==2.0.0`. You can use either one:

```python
# Works with all dash versions, but gives a warning with dash 2.0.0
import dash_html_components as html

# or

# Works with only dash>=2.0.0
from dash import html
```

There are no imports in the latest version of `dash-uploader` for `dash_html_components` - only in the examples. It could be that some older version *did*  have this kind of import, though. I'd rather not yet update the examples for the dash 2.0.0 as it's only 2 weeks old release and most of the users are still using older dash, and would receive an ImportError with the new import style. Perhaps after few months or a year the examples could be updated to use the new syntax.
