### ISSUE TITLE
Upload component not working when App is served with flask and  gunicorn/uwsgi/waitress

### ISSUE THREAD

**Issue by sorenwacker** [np-8/dash-uploader#53]
I have a login layer implemented with Flask, however, when that is active an the dash-app with the flask layer is served with one of gunicorn, waitress, uwsgi, the upload does not work anymore. If anyone has had the same issue and knows a solution please let me know.

**Comment by sorenwacker** [comment]
Luckily I found some hint:
```
fileError with resumable.js! (file, errorCount) l {flowObj: a, bytes: null, file: File, name: 'Blank_3.mzXML', size: 12331693, …} <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

**Comment by sorenwacker** [comment]
I think flask is blocking the access to API route.

**Comment by np-8** [comment]
Hi! Did you solve this? Is there anything that you'd need help with?

**Comment by sorenwacker** [comment]
Yes, I think it was my fault. The 'mzXML' format was not allowed, if I remember correctly.
