### ISSUE TITLE
dash uploader not working when adding in sidebar in layout

### ISSUE THREAD

**Issue by YuLin999** [np-8/dash-uploader#55]
I am new to Dash. Looks like the dash uploader stops working when I started using sidebar. The upload process does not start at all. I suspect this is because to render the sidebar page content I need to use url based pathname. Is this related to the other issue "Not working with url_base_pathname set in dash.Dash() "? But seems like this issue has already been addressed...

**Comment by np-8** [comment]
Thanks for the report! Could you please include steps how the problem could be reproduced?

**Comment by YuLin999** [comment]
Sorry! I think I made a mistake and this should not be the problem of sidebar.

**Comment by np-8** [comment]
Okay! Feel free to reopen this if you find any issues :)
