### ISSUE TITLE
Document how dash-uploader works under the hood (for dev)

### ISSUE THREAD

**Issue by np-8** [np-8/dash-uploader#65]
There should be some sort of document / diagram describing how dash-uploader works under the hood. This would improve the developer experience and make it easier for everyone to collaborate.

**Comment by fohrloop** [comment]
Now there is some sort of a diagram at [docs/CONTRIBUTING.md](https://github.com/np-8/dash-uploader/blob/dev/docs/CONTRIBUTING.md#7--how-does-dash-uploader-work-internally).
