### ISSUE TITLE
du.UploadStatus objects for du.callback

### ISSUE THREAD

**Issue by fohrloop** [np-8/dash-uploader#68]
In the dash-uploader 0.7.0 update, the new (proposed) callback syntax is

```python
@du.callback(
    output=Output('callback-output', 'children'),
    id='dash-uploader',
)
def get_a_list(status: du.UploadStatus):
    print(status.n_files_uploaded, status.n_files_total)
    return html.Ul([html.Li(x) for x in status.filenames])
```

### du.UploadStatus attributes 

The `du.UploadStatus` object could include

- `status.latest_file` (pathlib.Path): The full file path to the file that has been latest uploaded
- `status.uploaded_files` (list of pathlib.Path): The list of full file paths to all of the uploaded files. (uploaded in this session)
- `status.is_completed` (bool): True if all the files have been uploaded
- `status.n_uploaded` (int): The number of files already uploaded in this session
- `status.n_total` (int): The number of files to be uploaded.
- `status.uploaded_size_mb` (float):  Size of files uploaded in Megabytes
- `status.total_size_mb` (float):  Total size of files to be uploaded in Megabytes
- `status.upload_id` (str or None): The upload id used in the upload process, if any.
- `status.progress` (float): From 0 to 1, indicating the current upload progress of all files. From `flow.progress()`. Todo: Is this calculated based on amount of files or total file size?
- ~`status.timeremaining` (float): The remaining time to upload all files, in seconds. From `flow.timeRemaining()`.~ Dropped from the list (see  https://github.com/np-8/dash-uploader/issues/68#issuecomment-1046192895).

Goal: implement this `UploadStatus` class. It will serve as guide when implementing the `props` and `state` or the `Upload_ReactComponent` of the 0.7.0 release.

**Comment by fohrloop** [comment]
The `status.mb_uploaded` can be taken from `flow.sizeUploaded()`. The `status.mb_total` can be taken from `flow.getSize()`.

**Comment by fohrloop** [comment]
The `flow.timeRemaining()` seems a bit unstable. The number given by the flow component will need some filtering before the value would be displayed to the user. 

Here is a screen capture from situation where multiple files were "uploaded" (locally, no throttling). The `timeRemaining()` value jumped from 10s to ~20.000s when file was changed. This could be made working some day by keeping track of used time in the JS side and calculating longer time averages. As this is not priority right now, I'm dropping the attribute `status.timeremaining` from the list.

![image](https://user-images.githubusercontent.com/17479683/154835406-d010b740-6f01-4282-a2f4-6409ee1e9930.png)

**Comment by np-8** [comment]
Seems that some tricks are needed to make syntax this

```python
@du.callback(
    output=Output('callback-output', 'children'),
    id='dash-uploader',
)
def get_a_list(status: du.UploadStatus):
   # do smth
```

work, as I got this error:

```
dash.exceptions.InvalidCallbackReturnValue: The callback for `<Output `callback-output.children`>`
returned a value having type `UploadStatus`
which is not JSON serializable.


The value in question is either the only value returned,
or is in the top level of the returned list,

and has string representation
`<dash_uploader.uploadstatus.UploadStatus object at 0x000002681A132F40>`

In general, Dash properties can only be
dash components, strings, dictionaries, numbers, None,
or lists of those.
```
