### ISSUE TITLE
Can't upload a video from iphone

### ISSUE THREAD

**Issue by PandaGab** [np-8/dash-uploader#86]
Hello !

When I use the dash-uploader component inside a Chrome browser on a IPhone I am not able to upload a video using 'Take Video' option provided by the IPhone.

It will simply return the following message inside the component: "Invalid file type!"

Any ideas how to fix this ?

Thank you very much :)

**Comment by fohrloop** [comment]
My only guess would be that the selected filetype is not in the list of accepted filetypes. This is controlled by the `filetypes` argument of `du.Upload`. So, instead of:

```python
du.Upload(
    id="dash-uploader",
    filetypes=["csv", "xls", "xlsx"], # <-- remove this
    # .... rest
),
```

use 

```
du.Upload(
    id="dash-uploader",
    # .... rest
),
```

**Comment by PandaGab** [comment]
You were right, this change has worked !
```python
du.Upload(
    id="dash-uploader",
    filetypes=["mov"],
    # .... rest
)
```
